name: Scale Test

on: workflow_dispatch

jobs:
  test:
    runs-on: [self-hosted, asg-runner]
    timeout-minutes: 5    
    strategy:
      matrix:
        test: [1, 2, 3, 4, 5]
    steps:
      - run: echo "Running test ${{ matrix.test }}"
