name: Parallel Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5]

    steps:
      - name: Print Job ID
        run: echo "Running job ${{ matrix.job_id }}"

      - name: Simulate Work
        run: sleep 60
