name: test runner

on:
workflow_dispatch:

jobs:
test:
runs-on: self-hosted

```
strategy:
  matrix:
    job_id: [1, 2, 3, 4, 5]

steps:
  - name: Print Job Info
    run: |
      echo "Running job ${{ matrix.job_id }}"
      hostname
      sleep 120
```
